name: testtest
on:
  workflow_dispatch:
    inputs:
      urname:
        description: tell me your name
        required: true
        default: "nothing"
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  sonartest:
    uses: ramakrishnayelduti/testaction/.github/workflows/blank.yml@feat/test
    needs: build
    with:
      dirpath: testfolder1
      repocheckout: ${{ github.repository }}
